### ISSUE TITLE
Game crashes a few minutes after loading world

### ISSUE THREAD

**Issue by moscontheroad** [TeamOpenIndustry/ImmersiveRailroading#698]
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3882135/latest.log)
[crash-2019-11-22_22.13.46-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3882136/crash-2019-11-22_22.13.46-client.txt)

Hello again and sorry to hassle you with another report.

I updated to 1.7.2 on 1.12.2 and as the title says, my game crashes a few minutes after loading the world :S. 

Hope the info provided helps your dev, and thanks in advance.
[crash-2019-11-22_21.59.58-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3882128/crash-2019-11-22_21.59.58-client.txt)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3882130/latest.log)

**Comment by cam72cam** [comment]
That first file points at:
```
net.minecraftforge.client.event.RenderWorldLastEvent@36ab175f:
```

IR does not interact with that event.  Additionally the surrounding exception points at an optifine / thoumcraft issue.

**Comment by LoRes-Gamer** [comment]
Here's one that points to IR...(partial call stack)
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at cam72cam.mod.render.BlockRender.lambda$static$1(BlockRender.java:47)
	at java.lang.Iterable.forEach(Unknown Source)
	at cam72cam.mod.event.Event.execute(Event.java:14)
	at cam72cam.mod.event.ClientEvents$ClientEventBus.onClientTick(ClientEvents.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_818_ClientEventBus_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
[crash-2019-12-02_18.28.46-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3913764/crash-2019-12-02_18.28.46-client.txt)
[latest.log](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3913766/latest.log)

**Comment by LoRes-Gamer** [comment]
May also be related to #708 (matching stack trace), but mine is crashing at the end of world loading. Currently downgrading stepwise to see which version introduces the conflict. World was originally created (and track laid) using 1.6.1.

**Comment by LoRes-Gamer** [comment]
Game also crashed using IR 1.7.1 at same location, but loaded ok with 1.7.0 version of IR.

**Comment by ProsperCraft** [comment]
I just had a player crash on login with the same stacktrace-
https://paste.dimdev.org/hetamulewu.mccrash

ImmersiveRailroading-1.7.2_1.12.2

**Comment by ProsperCraft** [comment]
Another client crash - https://paste.dimdev.org/fagakuvage.mccrash

`Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at cam72cam.mod.render.BlockRender.lambda$static$1(BlockRender.java:47)
    at cam72cam.mod.render.BlockRender$$Lambda$317/471302922.run(Unknown Source)`

**Comment by ProsperCraft** [comment]
Just had another player with the same crash - https://paste.dimdev.org/radafoxihu.mccrash

**Comment by cam72cam** [comment]
Fixed in https://github.com/TeamOpenIndustry/UniversalModCore/commit/3db31f1d6f9be6e72d48e9ecde84bb95d1de879f.

It's due to some other mod messing with the loaded tile entity list in a place that it shouldn't.  This is a slight performance hit, but should fix the problem.

**Comment by ProsperCraft** [comment]
Please push this fix, I have trained my players too well, I get tons of these reports every day.

**Comment by TheNasbit** [comment]
When can we expect this fix to go live?

**Comment by andrboot** [comment]
The jar is built already, latest git jar. 
In terms of a ' release release' probably in a few weeks, though schedule is entirely a guesstimate.

**Comment by TheNasbit** [comment]
@andrboot 
Where can I find the already built .jar? Or do I have to build it on my own?

I took a download from [here](https://github.com/TeamOpenIndustry/ImmersiveRailroading/actions/runs/19902782) - but still receive the same error as said in the issue #698.

[Crash report](https://paste.dimdev.org/izerojiwez.mccrash)

**Comment by andrboot** [comment]
How does it work without loading optifine?

**Comment by andrboot** [comment]
Try https://github.com/TeamOpenIndustry/ImmersiveRailroading/actions/runs/31040376

**Comment by TheNasbit** [comment]
> Try https://github.com/TeamOpenIndustry/ImmersiveRailroading/actions/runs/31040376

Had no crashes so far... don't know if it was just "lucky" or fix... since there is no way to reproduce the crashes on will.

Should mention: Optifine is still enabled. So if it's fixed, then thanks to the new version you sent me.

**Comment by ProsperCraft** [comment]
This has resolved our client crashing as well.
