### ISSUE TITLE
Bugs(1.7.10,UniversalModCore,Trackapi,IRR

### ISSUE THREAD

**Issue by Ghostizockt** [TeamOpenIndustry/ImmersiveRailroading#915]
The Gui from the trains and the Immersive Railroading Tabs in the Inventory are Buggy,the Crosshair and Hotbar and Font is also buggy
![Screenshot_20210125-162311](https://user-images.githubusercontent.com/67050928/105726188-16294280-5f2a-11eb-9b6b-3335668c2868.png)
![Screenshot_20210125-162334](https://user-images.githubusercontent.com/67050928/105726196-175a6f80-5f2a-11eb-81c4-a51f92021d1e.png)
![Screenshot_20210125-162442](https://user-images.githubusercontent.com/67050928/105726197-17f30600-5f2a-11eb-8ce6-db2e15951362.png)

**Comment by Ghostizockt** [comment]
Pls Help me

**Comment by cam72cam** [comment]
That's an issue with the driver capabilities on the device you are using and can't be fixed by IR

**Comment by noyscjc-alt** [comment]
Please add support for the Immersive Railroading mod—even though mobile isn't currently supported—and I hope there won't be any bugs.

**Comment by noyscjc-alt** [comment]
I want to play Immersive Railroading 1.12.2, but suddenly a bug is turning the entire screen white; please fix this and update Immersive Railroading to the latest version (1.7.10 - 1.26)—and please, make sure there are no bugs.

**Comment by Goldenfield192** [comment]
> I want to play Immersive Railroading 1.12.2, but suddenly a bug is turning the entire screen white; please fix this and update Immersive Railroading to the latest version (1.7.10 - 1.26)—and please, make sure there are no bugs.

Use Zink renderer for less bugs
Mobile isn't currently focused (and in predictable future) due to graphic issues which IR lacks experts

**Comment by noyscjc-alt** [comment]
But I've already enabled the rendering 🤔, yet it's still the same 🙂‍↕️.
